{{cookiecutter.project_name}}-management:
  image: socialcode/{{cookiecutter.project_name}}:${VERSION}

  volumes:
    - /secrets:/secrets:ro

  environment:
    - SC_ENV=${SC_ENV}
    - SECRETS_FILES=/secrets/secrets.env
    - DATABASE_NAME={{cookiecutter.docker_compose__database_name__common}}
    - VERSION=${VERSION}

  env_file:
    - ${SC_ENV}.env